name: ReanimateMC
main: fr.jachou.reanimatemc.ReanimateMC
version: ${project.version}
description: A plugin that allows players to be knocked out and revived.
api-version: 1.20
authors:
  - Jachou
commands:
  reanimatemc:
    description: Main command for ReanimateMC
    usage: "/<command> <reload|revive|knockout|status|crawl|config> [player]"

permissions:
  reanimatemc.revive:
    description: Allows reviving a KO’d player
    default: true
  reanimatemc.execute:
    description: Allows executing a KO’d player
    default: true
  reanimatemc.bypass:
    description: Bypass KO and die instantly
    default: op
  reanimatemc.admin:
    description: Grants access to admin commands (reload, config, etc.)
    default: op
  reanimatemc.loot:
    description: Allows looting KO’d players’ inventories
    default: op

